### ISSUE TITLE
Clarifications on attribute mappings

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [outofdevops/ghshr-gcp-wlif#2]
I was wandering whether you have the time and will to provide some clarifications:

https://stackoverflow.com/questions/72752410/attribute-mappings-in-configuring-workload-identity-federation-between-gcp-and-g

Thank you very much in advance

**Comment by amasucci** [comment]
Hi @pantelis-karamolegkos, I just made another video to explain it in more details: https://youtu.be/fa9jHNaG4SA

Hope this helps,
Anto
